
title: "Léon's Personal Website"
baseurl: ""
url: "https://lasobrie.github.io"  # Replace with your actual GitHub Pages URL

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"   # try: air, contrast, dark, neon, sunrise, etc.
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# Top navigation (masthead menu)
header:
  nav: true


author:
  name: "Léon Sobrie, Ph.D."
  avatar: "/assets/images/picture_LeonS.jpg"
  bio: "Postdoctoral Researcher, Grado Department of Industrial & Systems Engineering, Virginia Tech"
  location: "Alexandria, Virginia, USA"
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope"
      url: "mailto:leonsobrie@vt.edu"
    - label: Google Scholar
      icon: "google-scholar"
      icon_pack: "ai"
      url: "https://scholar.google.com/citations?user=jsTt39AAAAAJ&hl=nl&oi=ao"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lasobrie"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/l%C3%A9on-sobrie-b1264a16b/"

include: ["_pages"]
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      classes: wide

masthead:
  title: "Léon Sobrie"

atom_feed:
  hide: true

# Ensure proper Markdown processing
# markdown: kramdown

# Add navigation links
#nav:
  #- title: "Home"
  #  url: /
  #- title: "Research"
   # url: /research/
  #- title: "Teaching"
   # url: /teaching/
  #- title: "Service"
   # url: /service/

# Enable relative links handling
# relative_links: true
